### ISSUE TITLE
Issue with using sprite.svg

### ISSUE THREAD

**Issue by alekslinde** [ben-rogerson/agency-webpack-mix-config#12]
@ben-rogerson I have a use-case which looks something like this:

```scss
.class{
 &:before{
  content: url("sprite.svg#icon-email");
 }
}
```

The `email.svg` is placed under icons directory. What will be a correct way to refer to SVG in SCSS?

I have also noticed that running `npm run dev` or `npm run build` will not generate `sprite.svg`. Not sure what could be the reason.
